// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCK2EUtaaFvlx7bBijcP_K6JJBLbu84Bow',
    appId: '1:134781274262:web:74c7f6869d959f89931ab7',
    messagingSenderId: '134781274262',
    projectId: 'trackizer-6bd5f',
    authDomain: 'trackizer-6bd5f.firebaseapp.com',
    storageBucket: 'trackizer-6bd5f.appspot.com',
    measurementId: 'G-XNENXBW4N4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQffI4YYpMq6acdmriYgCpFlDWgOojAyc',
    appId: '1:134781274262:android:1cdcc419be427547931ab7',
    messagingSenderId: '134781274262',
    projectId: 'trackizer-6bd5f',
    storageBucket: 'trackizer-6bd5f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYI8lbw3-no3CYrnDry1eOX9-ZB6-fDSw',
    appId: '1:134781274262:ios:35ea24d2c3533759931ab7',
    messagingSenderId: '134781274262',
    projectId: 'trackizer-6bd5f',
    storageBucket: 'trackizer-6bd5f.appspot.com',
    iosBundleId: 'com.example.cpExpenses',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYI8lbw3-no3CYrnDry1eOX9-ZB6-fDSw',
    appId: '1:134781274262:ios:4fc0be5a2a61f973931ab7',
    messagingSenderId: '134781274262',
    projectId: 'trackizer-6bd5f',
    storageBucket: 'trackizer-6bd5f.appspot.com',
    iosBundleId: 'com.example.cpExpenses.RunnerTests',
  );
}
